# Generated by Django 3.1.2 on 2020-10-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productivity',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('website', models.CharField(blank='False', max_length=100, null='False')),
                ('ec_partition_id', models.IntegerField(blank='False', null='False')),
                ('brand', models.CharField(blank='False', max_length=100, null='False')),
                ('brand_iteration', models.CharField(blank='False', max_length=100, null='False')),
                ('phase', models.CharField(blank='False', max_length=100, null='False')),
                ('user', models.CharField(blank='False', max_length=100, null='False')),
                ('task', models.CharField(blank='False', max_length=100, null='False')),
                ('sub_task', models.CharField(blank='False', max_length=100, null='False')),
                ('productivity', models.IntegerField(blank='False', null='False')),
                ('timestamp', models.DateTimeField(blank='True', null='True')),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pid',
            new_name='uid',
        ),
    ]
