# Generated by Django 3.1.2 on 2020-10-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_brand_ops'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_program',
            name='website_id',
            field=models.CharField(blank='False', max_length=20, null='False'),
            preserve_default='False',
        ),
    ]
