# Generated by Django 3.1.2 on 2020-10-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201027_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand_ops',
            old_name='backfill_nam_dropped',
            new_name='backfill_pt_count',
        ),
    ]
