# Generated by Django 3.1.2 on 2020-10-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201027_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivity',
            name='timestamp2',
            field=models.DateTimeField(blank='True', null='True'),
            preserve_default='True',
        ),
    ]
