# Generated by Django 3.1.2 on 2020-11-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_productivity_timestamp2'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_ops',
            name='mkpl',
            field=models.CharField(blank='False', max_length=45, null='False'),
            preserve_default='False',
        ),
    ]
