# Generated by Django 3.1.2 on 2020-11-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_brand_program_website_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_program',
            name='keys_count_gt_20',
            field=models.CharField(blank='False', max_length=20, null='False'),
        ),
    ]
