# Generated by Django 3.1.2 on 2020-11-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20201104_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_program',
            name='keys_count_gt_20',
            field=models.CharField(blank='False', max_length=25, null='False'),
        ),
    ]
