# Generated by Django 3.1.2 on 2020-11-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20201104_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_program',
            name='scrape_metric',
            field=models.CharField(blank='False', max_length=25, null='False'),
        ),
    ]
