# Generated by Django 3.1.2 on 2020-11-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20201104_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_program',
            name='vv_nam_dropped',
            field=models.CharField(blank='False', max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='brand_program',
            name='website_id',
            field=models.CharField(blank='False', max_length=20, null='False'),
            preserve_default='False',
        ),
    ]
