# Generated by Django 3.1.2 on 2020-11-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_brand_program_website_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand_program',
            name='website_id',
        ),
        migrations.AddField(
            model_name='brand_ops',
            name='backfill_request_date',
            field=models.DateField(blank='True', null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='brand_ops',
            name='bem_key_count',
            field=models.IntegerField(blank='False', null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='brand_ops',
            name='bem_required',
            field=models.CharField(blank='False', max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='brand_ops',
            name='bs_pt_not_found',
            field=models.CharField(blank='False', max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='brand_ops',
            name='validation_inaccurate_selection',
            field=models.IntegerField(blank='False', null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='brand_ops',
            name='validation_sample_selection',
            field=models.IntegerField(blank='False', null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='brand_ops',
            name='vv_nam_dropped',
            field=models.CharField(blank='False', max_length=20, null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='brand_ops',
            name='brand_iteration',
            field=models.CharField(blank='False', max_length=50, null='False'),
        ),
        migrations.AlterField(
            model_name='brand_ops',
            name='bsv_pt_not_found',
            field=models.CharField(blank='False', max_length=20, null='False'),
        ),
    ]
