# Generated by Django 3.1.2 on 2020-11-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20201106_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_program',
            name='website_id',
            field=models.CharField(blank='False', max_length=20, null='False'),
            preserve_default='False',
        ),
    ]
