# Generated by Django 3.1.3 on 2020-11-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_brand_ops_ec_partition_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand_ops',
            name='validation_inaccurate_selection',
        ),
        migrations.RemoveField(
            model_name='brand_ops',
            name='validation_sample_selection',
        ),
    ]
