# Generated by Django 3.1.3 on 2020-12-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20201201_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_program',
            name='en_nonen',
            field=models.CharField(blank='False', max_length=25, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='brand_program',
            name='month',
            field=models.DateField(blank='True', null='True'),
            preserve_default='True',
        ),
    ]
